version: 2.0

# heavily inspired by:
# https://raw.githubusercontent.com/pinax/pinax-wiki/6bd2a99ab6f702e300d708532a6d1d9aa638b9f8/.circleci/config.yml

common_go_v_1_13: &common_go_v_1_13
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: checkout fixtures submodule
        command: git submodule update --init --recursive
    - run:
        name: merge pull request base
        command: ./.circleci/merge_pr.sh
    - run:
        name: merge pull request base (2nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - run:
        name: merge pull request base (3nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - restore_cache:
        keys:
          - cache-v6-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - restore_cache:
        keys:
          - cache-v5-{{ arch }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: |
          pip install --user tox
          pip install --user checksumdir
    - run:
        name: install golang-1.13
        command: ./.circleci/install_golang.sh 1.13
    - run:
        name: run tox
        command: ~/.local/bin/tox
    - save_cache:
        paths:
          - .hypothesis
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: cache-v6-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - save_cache:
        paths:
          - ~/.ethash
        key: cache-v5-{{ arch }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  py35-install-geth-v1.9.14:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.9.14
          TOXENV: py35-install-geth-v1.9.14
  py36-install-geth-v1.9.14:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.6
        environment:
          GETH_VERSION: v1.9.14
          TOXENV: py36-install-geth-v1.9.14
  py37-install-geth-v1.9.14:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.7
        environment:
          GETH_VERSION: v1.9.14
          TOXENV: py37-install-geth-v1.9.14
  py35-install-geth-v1.9.15:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.9.15
          TOXENV: py35-install-geth-v1.9.15
  py36-install-geth-v1.9.15:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.6
        environment:
          GETH_VERSION: v1.9.15
          TOXENV: py36-install-geth-v1.9.15
  py37-install-geth-v1.9.15:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.7
        environment:
          GETH_VERSION: v1.9.15
          TOXENV: py37-install-geth-v1.9.15
  py35-install-geth-v1.9.16:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.9.16
          TOXENV: py35-install-geth-v1.9.16
  py36-install-geth-v1.9.16:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.6
        environment:
          GETH_VERSION: v1.9.16
          TOXENV: py36-install-geth-v1.9.16
  py37-install-geth-v1.9.16:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.7
        environment:
          GETH_VERSION: v1.9.16
          TOXENV: py37-install-geth-v1.9.16
  py35-install-geth-v1.9.17:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.9.17
          TOXENV: py35-install-geth-v1.9.17
  py36-install-geth-v1.9.17:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.6
        environment:
          GETH_VERSION: v1.9.17
          TOXENV: py36-install-geth-v1.9.17
  py37-install-geth-v1.9.17:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.7
        environment:
          GETH_VERSION: v1.9.17
          TOXENV: py37-install-geth-v1.9.17
  py35-install-geth-v1.9.18:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.9.18
          TOXENV: py35-install-geth-v1.9.18
  py36-install-geth-v1.9.18:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.6
        environment:
          GETH_VERSION: v1.9.18
          TOXENV: py36-install-geth-v1.9.18
  py37-install-geth-v1.9.18:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.7
        environment:
          GETH_VERSION: v1.9.18
          TOXENV: py37-install-geth-v1.9.18
  py35-install-geth-v1.9.19:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.9.19
          TOXENV: py35-install-geth-v1.9.19
  py36-install-geth-v1.9.19:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.6
        environment:
          GETH_VERSION: v1.9.19
          TOXENV: py36-install-geth-v1.9.19
  py37-install-geth-v1.9.19:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.7
        environment:
          GETH_VERSION: v1.9.19
          TOXENV: py37-install-geth-v1.9.19
  py35-install-geth-v1.9.20:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.9.20
          TOXENV: py35-install-geth-v1.9.20
  py36-install-geth-v1.9.20:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.6
        environment:
          GETH_VERSION: v1.9.20
          TOXENV: py36-install-geth-v1.9.20
  py37-install-geth-v1.9.20:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.7
        environment:
          GETH_VERSION: v1.9.20
          TOXENV: py37-install-geth-v1.9.20
  py35-install-geth-v1.9.21:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.9.21
          TOXENV: py35-install-geth-v1.9.21
  py36-install-geth-v1.9.21:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.6
        environment:
          GETH_VERSION: v1.9.21
          TOXENV: py36-install-geth-v1.9.21
  py37-install-geth-v1.9.21:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.7
        environment:
          GETH_VERSION: v1.9.21
          TOXENV: py37-install-geth-v1.9.21
  py35-install-geth-v1.9.22:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.9.22
          TOXENV: py35-install-geth-v1.9.22
  py36-install-geth-v1.9.22:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.6
        environment:
          GETH_VERSION: v1.9.22
          TOXENV: py36-install-geth-v1.9.22
  py37-install-geth-v1.9.22:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.7
        environment:
          GETH_VERSION: v1.9.22
          TOXENV: py37-install-geth-v1.9.22
  py35-install-geth-v1.9.23:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.9.23
          TOXENV: py35-install-geth-v1.9.23
  py36-install-geth-v1.9.23:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.6
        environment:
          GETH_VERSION: v1.9.23
          TOXENV: py36-install-geth-v1.9.23
  py37-install-geth-v1.9.23:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.7
        environment:
          GETH_VERSION: v1.9.23
          TOXENV: py37-install-geth-v1.9.23
  py35-install-geth-v1.9.24:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.9.24
          TOXENV: py35-install-geth-v1.9.24
  py36-install-geth-v1.9.24:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.6
        environment:
          GETH_VERSION: v1.9.24
          TOXENV: py36-install-geth-v1.9.24
  py37-install-geth-v1.9.24:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.7
        environment:
          GETH_VERSION: v1.9.24
          TOXENV: py37-install-geth-v1.9.24
  py35-install-geth-v1.9.25:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.9.25
          TOXENV: py35-install-geth-v1.9.25
  py36-install-geth-v1.9.25:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.6
        environment:
          GETH_VERSION: v1.9.25
          TOXENV: py36-install-geth-v1.9.25
  py37-install-geth-v1.9.25:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.7
        environment:
          GETH_VERSION: v1.9.25
          TOXENV: py37-install-geth-v1.9.25
  py35-install-geth-v1.10.0:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.10.0
          TOXENV: py35-install-geth-v1.10.0
  py36-install-geth-v1.10.0:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.6
        environment:
          GETH_VERSION: v1.10.0
          TOXENV: py36-install-geth-v1.10.0
  py37-install-geth-v1.10.0:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.7
        environment:
          GETH_VERSION: v1.10.0
          TOXENV: py37-install-geth-v1.10.0
  py35-install-geth-v1.10.1:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.10.1
          TOXENV: py35-install-geth-v1.10.1
  py36-install-geth-v1.10.1:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.6
        environment:
          GETH_VERSION: v1.10.1
          TOXENV: py36-install-geth-v1.10.1
  py37-install-geth-v1.10.1:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.7
        environment:
          GETH_VERSION: v1.10.1
          TOXENV: py37-install-geth-v1.10.1
  py35-install-geth-v1.10.2:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.10.2
          TOXENV: py35-install-geth-v1.10.2
  py36-install-geth-v1.10.2:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.6
        environment:
          GETH_VERSION: v1.10.2
          TOXENV: py36-install-geth-v1.10.2
  py37-install-geth-v1.10.2:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.7
        environment:
          GETH_VERSION: v1.10.2
          TOXENV: py37-install-geth-v1.10.2
  py35-install-geth-v1.10.3:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.10.3
          TOXENV: py35-install-geth-v1.10.3
  py36-install-geth-v1.10.3:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.6
        environment:
          GETH_VERSION: v1.10.3
          TOXENV: py36-install-geth-v1.10.3
  py37-install-geth-v1.10.3:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.7
        environment:
          GETH_VERSION: v1.10.3
          TOXENV: py37-install-geth-v1.10.3

  py34-lint:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.4
        environment:
          TOXENV: py34-lint
  py35-lint:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.5
        environment:
          TOXENV: py35-lint
  py36-lint:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-lint
  py37-lint:
    <<: *common_go_v_1_13
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-lint


workflows:
  version: 2
  test:
    jobs:
      - py35-install-geth-v1.9.14
      - py36-install-geth-v1.9.14
      - py37-install-geth-v1.9.14

      - py35-install-geth-v1.9.15
      - py36-install-geth-v1.9.15
      - py37-install-geth-v1.9.15

      - py35-install-geth-v1.9.16
      - py36-install-geth-v1.9.16
      - py37-install-geth-v1.9.16

      - py35-install-geth-v1.9.17
      - py36-install-geth-v1.9.17
      - py37-install-geth-v1.9.17

      - py35-install-geth-v1.9.18
      - py36-install-geth-v1.9.18
      - py37-install-geth-v1.9.18

      - py35-install-geth-v1.9.19
      - py36-install-geth-v1.9.19
      - py37-install-geth-v1.9.19

      - py35-install-geth-v1.9.20
      - py36-install-geth-v1.9.20
      - py37-install-geth-v1.9.20

      - py35-install-geth-v1.9.21
      - py36-install-geth-v1.9.21
      - py37-install-geth-v1.9.21

      - py35-install-geth-v1.9.22
      - py36-install-geth-v1.9.22
      - py37-install-geth-v1.9.22

      - py35-install-geth-v1.9.23
      - py36-install-geth-v1.9.23
      - py37-install-geth-v1.9.23

      - py35-install-geth-v1.9.24
      - py36-install-geth-v1.9.24
      - py37-install-geth-v1.9.24

      - py35-install-geth-v1.9.25
      - py36-install-geth-v1.9.25
      - py37-install-geth-v1.9.25

      - py35-install-geth-v1.10.0
      - py36-install-geth-v1.10.0
      - py37-install-geth-v1.10.0

      - py35-install-geth-v1.10.1
      - py36-install-geth-v1.10.1
      - py37-install-geth-v1.10.1

      - py35-install-geth-v1.10.2
      - py36-install-geth-v1.10.2
      - py37-install-geth-v1.10.2

      - py35-install-geth-v1.10.3
      - py36-install-geth-v1.10.3
      - py37-install-geth-v1.10.3

      - py35-lint
      - py36-lint
      - py37-lint
